# Generated by Django 3.0.4 on 2020-04-05 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0002_auto_20200402_1206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citizen',
            old_name='location',
            new_name='address',
        ),
    ]
