# Generated by Django 3.0.4 on 2020-04-07 08:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('citizens', '0003_auto_20200405_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='supervisor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('temperature', models.FloatField(validators=[django.core.validators.MinValueValidator(34.0), django.core.validators.MaxValueValidator(42.0)])),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='citizens.Citizen')),
            ],
        ),
    ]
