# Generated by Django 3.0.4 on 2020-04-07 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0004_auto_20200407_0855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citizen',
            old_name='supervisor',
            new_name='creator',
        ),
    ]
