# Generated by Django 3.0.4 on 2020-04-07 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0005_auto_20200407_0859'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='temperature',
            options={'ordering': ['created']},
        ),
    ]
