# Generated by Django 3.0.4 on 2020-04-07 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0006_auto_20200407_0913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temperature',
            old_name='user',
            new_name='citizen',
        ),
    ]
