# Generated by Django 3.0.4 on 2020-04-08 08:41

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0007_auto_20200407_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationPhoneNumberRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('verification_code', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
