# Generated by Django 3.0.4 on 2020-04-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0008_verificationphonenumberrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='doc_type',
            field=models.CharField(choices=[('P', 'Passport'), ('C', 'ID card'), ('D', 'Driver licence')], default='P', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='citizen',
            name='document',
            field=models.CharField(default='test', max_length=16),
            preserve_default=False,
        ),
    ]
