# Generated by Django 3.0.4 on 2020-04-09 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0009_auto_20200408_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citizen',
            name='creator',
        ),
    ]
