# Generated by Django 3.0.4 on 2020-04-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0011_citizen_full_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='hash',
            field=models.CharField(default='pbkdf2_sha256$180000$Slava urkaine!$+2CYvxmH+uZdgiyZV2JgGMTSJ45pP06MW4S+msmpOCI=', max_length=256, unique=True),
        ),
    ]
