# Generated by Django 3.0.4 on 2020-04-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0013_remove_temperature_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='image',
            field=models.CharField(default='', max_length=4096),
            preserve_default=False,
        ),
    ]
