# Generated by Django 3.0.4 on 2020-04-10 18:03

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0015_auto_20200410_1734'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='citizen',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='citizens_ci_search__70b01e_gin'),
        ),
    ]
