# Generated by Django 3.0.4 on 2020-04-11 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0016_auto_20200410_1803'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='citizen',
            name='citizens_ci_search__70b01e_gin',
        ),
        migrations.RemoveField(
            model_name='citizen',
            name='search_vector',
        ),
        migrations.AddField(
            model_name='citizen',
            name='full_text',
            field=models.CharField(default='<django.db.models.fields.CharField><phonenumber_field.modelfields.PhoneNumberField>', max_length=130),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='citizen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='temperature_history', to='citizens.Citizen'),
        ),
    ]
