# Generated by Django 3.0.4 on 2020-04-13 14:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0019_auto_20200411_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperature',
            name='timecode',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
